added password reset approval
StrikeProtocols/strike-security-ios pull request #51
Opened 2022-08-10 21:33 UTC by bflood-strike

2022-08-11 14:38 UTC, ata-peppered requested changes

2022-08-11 14:38 UTC, ata-peppered commented on Strike/Models/Solana/ApprovalDispositionRequest+SolanaSignable.swift
> +            return "".data(using: .utf8)!
would we need to sign the email for this request to complete?

2022-08-12 02:18 UTC, bholzman commented on Strike/Models/Solana/ApprovalDispositionRequest+SolanaSignable.swift
> +            return "".data(using: .utf8)!
The endpoint in brooklyn doesn't need that -- the jwt token has to be signed with the key anyway, so not sure what that would add

2022-08-12 14:39 UTC, bflood-strike commented on Strike/Models/Solana/ApprovalDispositionRequest+SolanaSignable.swift
> +            return "".data(using: .utf8)!
what Ben said - the server does not check any signature other than the jwt token being signed in this case.

2022-08-15 16:55 UTC, ata-peppered approved these changes

2022-08-15 16:55 UTC, merged